Figaro.require_keys(
  "admin_email",
  "cookie_expiry_days",
  "host",
  "reset_token_valid_hours",
  "signup_credits",
  "ask_question_credit",
  "minimum_content_length",
  "net_upvotes_for_answer",
  "credits_for_answer",
  "STRIPE_PUBLISHABLE_KEY",
  "STRIPE_SECRET_KEY",
  "public_api_request_limit"
)
